name: Main
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  Project Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"
      - name: Install dependencies
        run: npm install decheck
      - name: Start Analysis
        run: npx decheck

        